verbose = false;
MEXOPTS={'-largeArrayDims','-DMEX'};
if verbose
  MEXOPTS={'-v',MEXOPTS{:}};
end
MSSE42='CXXFLAGS=$CXXFLAGS -msse4.2';
STDCPP11='CXXFLAGS=$CXXFLAGS -std=c++11';

ELTOPO_INC= sprintf('-I%s/',path_to_eltopo);
ELTOPO_LIB= strsplit(sprintf('-L%s/eltopo3d -leltopo_release',path_to_eltopo));
CLANG={'CXX=/usr/bin/clang++','LD=/usr/bin/clang++'};
FRAMEWORK_LDFLAGS='LDFLAGS=\$LDFLAGS -framework Foundation -framework AppKit -framework Accelerate';
NOOPT_LDOPTIMFLAGS='LDOPTIMFLAGS="-O "';

% See libigl documentation. In short, Libigl is a header-only library by
% default: no compilation needed (like Eigen). There's an advanced **option**
% to precompile libigl as a static library. This cuts down on compilation time.
% It is optional and more difficult to set up. Set this to true only if you
% know what you're doing.
use_libigl_static_library = exist([path_to_libigl '/lib/libigl.a'],'file')~=0;
%use_libigl_static_library  = false;
if use_libigl_static_library
  r = -1;
  cmd = sprintf('cd "%s"/lib && /usr/local/bin/cmake ../optional/ -DLIBIGL_USE_STATIC_LIBRARY=ON -DLIBIGL_WITH_ANTTWEAKBAR=ON -DLIBIGL_WITH_BBW=ON -DLIBIGL_WITH_CORK=ON -DLIBIGL_WITH_CGAL=ON -DLIBIGL_WITH_COMISO=ON -DLIBIGL_WITH_EMBREE=ON -DLIBIGL_WITH_LIM=ON -DLIBIGL_WITH_MATLAB=ON -DLIBIGL_WITH_MOSEK=ON -DLIBIGL_WITH_NANOGUI=OFF -DLIBIGL_WITH_OPENGL=ON -DLIBIGL_WITH_PNG=ON -DLIBIGL_WITH_TETGEN=ON -DLIBIGL_WITH_TRIANGLE=ON -DLIBIGL_WITH_VIEWER=ON -DLIBIGL_WITH_XML=ON -DCMAKE_BUILD_TYPE=Release && make -j3',path_to_libigl);
  if verbose
    fprintf('%s\n',cmd);
  end
  [r,c] = system(cmd);
  use_libigl_static_library = r == 0;
end
%use_libigl_static_library= false;
LIBIGL_INC=sprintf('-I%s/include',path_to_libigl);
if use_libigl_static_library
  LIBIGL_FLAGS='-DIGL_STATIC_LIBRARY';
  LIBIGL_LIB=strsplit(sprintf('-L%s/lib -ligl',path_to_libigl));
  LIBIGL_LIBEMBREE='-liglembree';
  LIBIGL_LIBMATLAB='-liglmatlab';
  LIBIGL_LIBCGAL='-liglcgal';
  LIBIGL_LIBCORK='-liglcork';
else
  % `mex` has a silly requirement that arguments be non-empty, hence the NOOP
  % defines
  LIBIGL_FLAGS='-DIGL_SKIP';
  LIBIGL_LIB={'-DIGL_SKIP'};
  LIBIGL_LIBMATLAB='-DIGL_SKIP';
  LIBIGL_LIBEMBREE='-DIGL_SKIP';
  LIBIGL_LIBCGAL='-DIGL_SKIP';
  LIBIGL_LIBCORK='-DIGL_SKIP';
end
LIBIGL_BASE={LIBIGL_INC,LIBIGL_FLAGS,LIBIGL_LIB{:},LIBIGL_LIBMATLAB};

if exist(sprintf('%s/external/nanogui/ext/eigen/',path_to_libigl))
  EIGEN_INC=sprintf('-I%s/external/nanogui/ext/eigen/',path_to_libigl);
elseif exist('/usr/local/include/eigen3')
  EIGEN_INC='-I/usr/local/include/eigen3';
elseif exist('/opt/local/include/eigen3')
  EIGEN_INC='-I/opt/local/include/eigen3';
end

EMBREE=[path_to_libigl '/external/embree'];
EMBREE_INC=strsplit(sprintf('-I%s -I%s/include/',EMBREE,EMBREE));
EMBREE_LIB=strsplit(sprintf('-L%s/build -lembree -lsys -lembree_avx -lembree_avx2 -lembree_sse42 -llexers -lsimd',EMBREE));

CORK_INC=sprintf('-I%s/src',[path_to_libigl '/external/cork']);
CORK_LIB=strsplit(sprintf('-L%s -lcork',[path_to_libigl '/lib']));

TINYXML2=[path_to_libigl '/external/tinyxml2'];
TINYXML2_INC=sprintf('-I%s/',TINYXML2);
TINYXML2_LIB=strsplit(sprintf('-L%s/ -ltinyxml2',TINYXML2));

if exist('/usr/local/include/CGAL')
  CGAL='/usr/local/';
elseif exist('/opt/local/include/CGAL')
  CGAL='/opt/local/';
end
CGAL_INC=sprintf('-I%s/include',CGAL);
CGAL_LIB=strsplit(sprintf('-L%s/lib -lCGAL -lCGAL_Core -lgmp -lmpfr',CGAL));
CGAL_FLAGS='CXXFLAGS=\$CXXFLAGS -frounding-math';

BOOST='/usr/local/';
BOOST_INC=sprintf('-I%s/include',BOOST);
BOOST_LIB=strsplit(sprintf('-L%s/lib -lboost_thread-mt -lboost_system-mt',BOOST));

warning([ ...
  'This is **VERY** experimental. In principle, this should compile all ', ...
  'of the mex functions in this directory. In practice, users will ', ...
  'surely have to adjust paths and flags at the top of this file.']);
input('Hit any key to continue...');

out_of_date = @(prefix) ...
  ~exist(['./' prefix '.mexmaci64'],'file') || ...
  (datenum(getfield(dir([prefix '.cpp']),'date')) > ...
  datenum(getfield(dir([prefix '.mexmaci64']),'date'))) ||  ...
  (use_libigl_static_library  &&  ...
  datenum(getfield(dir([path_to_libigl '/lib/libigl.a']),'date')) > ...
  datenum(getfield(dir([prefix '.mexmaci64']),'date')));

prefixes = { ...
  'ambient_occlusion', ...
  'bone_visible', ...
  'bone_visible_embree', ...
  'collapse_small_triangles', ...
  'decimate_cgal', ...
  'decimate_libigl', ...
  'eltopo', ...
  'fit_rotations_mex', ...
  'in_element_aabb', ...
  'intersect_other', ...
  'mesh_boolean', ...
  'outer_hull', ...
  'point_mesh_squared_distance', ...
  'ray_mesh_intersect', ...
  'read_mesh_from_xml', ...
  'reorient_facets', ...
  'selfintersect', ...
  'signed_distance', ...
  'signed_distance_isosurface', ...
  'simplify_polyhedron', ...
  'slim', ...
  'solid_angle' };

for prefix = prefixes
  prefix = prefix{1};
  if out_of_date(prefix)
    try
      mex( ...
         MEXOPTS{:},...
         MSSE42, ...
         STDCPP11, ...
         EIGEN_INC, ...
         ELTOPO_INC, ...
         ELTOPO_LIB{:}, ...
         FRAMEWORK_LDFLAGS, ...
         LIBIGL_BASE{:}, ...
         LIBIGL_LIBEMBREE, ...
         LIBIGL_LIBCGAL, ...
         LIBIGL_LIBCORK, ...
         EMBREE_INC{:}, EMBREE_LIB{:}, ...
         CORK_INC,CORK_LIB{:}, ...
         TINYXML2_INC,TINYXML2_LIB{:}, ...
         CGAL_INC,CGAL_LIB{:},CGAL_FLAGS, ...
         BOOST_INC,BOOST_LIB{:}, ...
        [prefix '.cpp']);
     catch ME
       warning(ME.identifier,ME.message);
     end
  end
end

% ONE-OFFs

% impaste is currently only implemented for mac
if ismac
  mex( ...
    MEXOPTS{:}, MSSE42, STDCPP11, ...
    CLANG{:},NOOPT_LDOPTIMFLAGS,FRAMEWORK_LDFLAGS, ...
    '-output','impaste','impaste.cpp','paste.mm');
end

mex( ...
  MEXOPTS{:}, MSSE42, STDCPP11, ...
  LIBIGL_BASE{:},EIGEN_INC, ...
  '-Iwinding_number', ...
  '-output','winding_number', ...
  'winding_number.cpp','winding_number/parse_rhs.cpp','winding_number/prepare_lhs.cpp');
