function [UV,F, res, edge_norms] = ...
  create_irregular_grid_with_min_angle( ...
    xRes, yRes, n, xWrap, yWrap, min_angle, ...
    no_interior, dart_threshold)
  % Deprecated. 
  %
  % See also: create_irregular_grid

  warning('Deprecated. Call create_irregular_grid directly');
  [UV,F, res, edge_norms] = create_irregular_grid( ...
    xRes,yRes, ...
    'NumDarts',n,'xWrap',xWrap,'yWrap',yWrap, ...
    'MinAngle',min_angle,'NoInterior',no_interior, ...
    'DartThreshold',dart_threshold);
end
