function png2objandtga( ...
  filename, ...
  laplacian_smoothness_iterations, ...
  max_points_on_boundary)
% png2objandtga(filename,laplacian_smoothness_iterations,max_points_on_boundary)
  basename = regexprep(filename,'\.png$','');
  img = imread(filename);
  if(0 ~= mod(size(img,1),4) || 0 ~= mod(size(img,2),4))
    warning(['Image dimensions are not a multiple of 4...' ...
      ' tga may not load in openGL properly']);
  end
  [V,F] = png2mesh( ...
    filename, ...
    laplacian_smoothness_iterations, ...
    max_points_on_boundary);
  tsurf(F,V);
  V = [V(:,1) V(:,2) 0*V(:,1)];
  writeOBJ([basename '.obj'],V,F);
  % convert png to tga
  path_to_convert = '/opt/local/bin/convert';
  [status, result] = ...
    system(['export DYLD_LIBRARY_PATH="";' path_to_convert ' -flatten ' basename '.png' ' ' basename '.tga']);
  [status, result] = ...
    system(['export DYLD_LIBRARY_PATH="";' path_to_convert ' +matte ' basename '.tga' ' ' basename '.tga']);
end
