function writeSVG(filename,V,E,F,S,W)
  %
  % writeSVG(filename,V,E,F,S,W)
  %
  % Inputs:
  %   V  #V by 2 list of vertex positions
  %   E  #E by 2 list of edge indices into V
  %   F  #E by 3 list of decimal fill color values
  %   S  #E by 3 list of decimal stroke color values
  %   W  #E by 1 list of stroke width values
  % Example:
  %   writeSVG('wolf-rods.svg',svg.V,svg.E,svg.F,svg.S,svg.W);
  %   !cat wolf-rods.svg | sed -e "s/fill:[^;]*;//g" | /usr/local/bin/cairosvg - -o wolf-rods.pdf
  %
  fh = fopen(filename,'w');
  %fprintf(fh,['<svg xmlns="http://www.w3.org/2000/svg" baseProfile="full"' ...
  %  ' version="1.1" width="100%%" height="100%%" viewBox="%f %f %f %f"' ...
  %  ' xmlns:xlink="http://www.w3.org/1999/xlink" >\n'],min(V),max(V)-min(V));
  %fprintf(fh,['<svg version="1.1" id="Layer_1" ' ...
  %  ' xmlns="http://www.w3.org/2000/svg" ' ...
  %  ' xmlns:xlink="http://www.w3.org/1999/xlink" ' ...
  %  ' x="%dmm" y="%dmm" ' ...
  %  ' viewBox="%d %d %d %d" style="enable-background:new %d %d %d %d;"' ...
  %  ' xml:space="preserve">\n'], [min(V) repmat([min(V) max(V)-min(V)],1,2)]);
  fprintf(fh,['<svg version="1.1" id="Layer_1" ' ...
    ' xmlns="http://www.w3.org/2000/svg" ' ...
    ' xmlns:xlink="http://www.w3.org/1999/xlink" ' ...
    ' width="%dmm" height="%dmm" ' ...
    ' xml:space="preserve">\n'], max(V)-min(V));
  fprintf(fh, ...
    ['<line x1="%fmm" y1="%fmm" x2="%fmm" y2="%fmm" ' ...
    'style="fill:rgb(%d,%d,%d);stroke:rgb(%d,%d,%d);stroke-width:%d" />'], ...
    [V(E(:,1),:) V(E(:,2),:) round(255*[F S]) W]');
  fprintf(fh,'</svg>\n');
  fclose(fh);
end
